### ISSUE TITLE
Compatilibity with Orchestrator on-prem v2023.10.6

### ISSUE THREAD

**Issue by J0ska** [UiPath/uipathcli#136]
Hi,
I am trying to connect with this tool to Orchestrator on-prem v2023.10.6
I set-up everything accordingly to use "Client Credentials" authentication method.
I set-up the external application scope according notes in issue #86.
Still I can't connect.

First I am getting "UnsupportedApiVersion" error.
Z:\>uipath orchestrator users get
Error retrieving bearer token: Token service returned status code '405' and body '{"error":{"code":"UnsupportedApiVersion","message":"The HTTP resource that matches the request URI 'https://orchestrator.***.com/identity_/connect/token' does not support HTTP method 'POST'.","innerError":null}}'

After adding "--identity-uri" option I ma getting just some garbage:
Z:\>uipath orchestrator users get --identity-uri https://orchestrator.***.com/identity

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <meta name="referrer" content="no-referrer" />

Is Orchestrator on-prem v2023.10.6 supported?
If yes, any idea what I am doing wrong?

Thx
Josef

**Comment by thschmitt** [comment]
Yeah, 23.10 should work. Could you try out adding a `/` at the end of the Uri which should omit the org and tenant?

e.g.
```
profiles:
- name: default
  organization: default
  tenant: default
  uri: https://orchestrator.***.com/
  auth:
    clientId: 3ef87e83-3a3e-436c-82ba-7246f7e2c1be
    clientSecret: <redacted>
    uri: https://orchestrator.***.com/identity
```
