### ISSUE TITLE
Using config set function for clientID and clientSecret

### ISSUE THREAD

**Issue by MaxwellChittenden** [UiPath/uipathcli#141]
is there anyway to set the clientID and clientSecret from the command line like the config set function does? 
I'm trying to integrate this into a cicd pipeline that does not allow for interactive commands.

**Comment by mikael-andersson91** [comment]
> There is currently no config set operation which allows you to set the client id or client secret but you can set the environment variables `UIPATH_CLIENT_ID` and `UIPATH_CLIENT_SECRET` to avoid interactive commands. Hope this helps!

Which environment variables would I need to set for the external application scope and organization when using the CLI in this way?

Not having a direct way of setting the client id, secret, scope and organization in a non-interactive way is a huge limitation when using this tool in an automated way (for example in GitHub Actions or other pipelines as mentioned above)

**Comment by willie013** [comment]
Hi! I am running into the same issue when trying to integrate this with a CICD pipeline. Did you manage to do some testing yet with the global variables @mikael-andersson91 ?

**Comment by mikael-andersson91** [comment]
> Hi! I am running into the same issue when trying to integrate this with a CICD pipeline. Did you manage to do some testing yet with the global variables [@mikael-andersson91](https://github.com/mikael-andersson91) ?
> 
> _Update:_
> 
> Setting the environment variables and running the uipathcli executable after that seems to work for my usecase:
> 
> > ```
> > # Set environment variables for UiPath CLI
> > - Write-Host "Setting UiPath CLI environment variables"
> > - $env:UIPATH_CLIENT_ID="$env:UIPATH_APPLICATION_ID"
> > - $env:UIPATH_CLIENT_SECRET="$env:UIPATH_APPLICATION_SECRET"
> > - $env:UIPATH_ORGANIZATION="****"
> > - $env:UIPATH_TENANT="Development"
> > - ./uipath studio package pack --source "$env:CI_PROJECT_DIR\project.json" --destination "$env:CI_PROJECT_DIR\output_packages" --auto-version true --debug
> > ```
> 
> > uipcli Information: 0 : Packaged project TestProcesX v1.0.194278442 saved to C:\GitLab-Runner\builds\t2_kzDn3z\0\rpa\gitpipelines\gitpipelinesproject\output_packages.
> > {
> > "description": "_**",
> > "error": null,
> > "name": "**__",
> > "output": "C:\GitLab-Runner\builds\t2_kzDn3z\0\_***\output_packages\TestProcesX.1.0.194278442.nupkg",
> > "projectId": "",
> > "status": "Succeeded",
> > "version": "1.0.194278442"
> > }

This looks very similar to what I experimented with when setting up the tool on GitHub Actions:

```yml
uipathcli-sample-job:
  env:
    UIPATH_CLIENT_ID: ${{ secrets.CLIENT_ID }}
    UIPATH_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    UIPATH_ORGANIZATION: ${{ secrets.ORGANIZATION }}
    UIPATH_TENANT: ${{ secrets.TENANT }}
  steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4

## Insert CLI installation steps here

    - id: sample-uipath-command
      run: |
        uipath orchestrator folders get
```

By setting the environment variables like this I was able to get it to work.
