### ISSUE TITLE
Support for Confidential apps with user scopes (authorization code flow)

### ISSUE THREAD

**Issue by thongmap** [UiPath/uipathcli#192]
Hi is it possible for the cli to authenticate with Orchestrator via the Confidential apps with user scopes (authorization code flow) ?

**Comment by thongmap** [comment]
Thanks for the quick update @thschmitt , I have tried and it's working as expected although i would like to have a config where i can input the identity uri besides from using the flag --identity-uri

**Comment by thschmitt** [comment]
You should be able to either set the environment variable `UIPATH_IDENTITY_URI` or add the `auth.uri` property in the config file, e.g.

```
profiles:
- name: default
  organization: <your-org>
  tenant: defaulttenant
  auth:
    uri: https://<your-server>/identity_
```
